### ISSUE TITLE
Set up Docker Compose

### ISSUE THREAD

**Issue by kweerious** [WFTDA/bouttime#130]
- [ ] Remove old fig.yml
- [ ] Use docker-compose (critical for when we have fixtures/db involved)
- [ ] Add .dockerignore

**Comment by chooban** [comment]
I'd like to take a run at this, if you like? I've done some docker stuff recently and it'd nice to see if what I've learned applies to other projects.

**Comment by miketheman** [comment]
@chooban Certainly! There's an existing fig.yml that could be a decent starting point.

There's currently only the single container, so it should be straightforward.

The important functionality is currently hidden in the `onbuild` approach.

**Comment by chooban** [comment]
Not so much "laugh" as "Cool, I'll get on with it!". :)
